### ISSUE TITLE
Feature missing

### ISSUE THREAD

**Issue by bokrma** [manjunathasm/email-engine-core-service#1]
Hello!
as i noticed, i can't see the realtime syncing of changes when an email got moved from one mailbox to another or a new email received or deleted
there should be handling for the update realtime/near realtime with expecting that the system will have thousands of accounts

**Comment by manjunathasm** [comment]
Hi @bokrma 

I have added the realtime sync with subscriber mechanism to get notify if any changes made in the mailbox. 

Note: To get realtime mailbox updates you need to host this application, because the outlook should notify the changes to the application.

Thanks for highlighting the issue.
